import type { ListingRow, SettingsRow } from '@af/shared';

export function listing(over: Partial<ListingRow> = {}): ListingRow {
  return {
    id: over.id ?? 'id-1',
    dedupe_key: 'k',
    title: '2027 Data Science Apprentice - Crawley',
    employer_id: null,
    employer_name: 'Thales UK Limited',
    url: 'https://www.findapprenticeship.service.gov.uk/apprenticeship/reference/2000057249',
    apply_url: 'https://thales.wd3.myworkdayjobs.com/x',
    level: 6,
    level_source: 'source',
    is_degree: true,
    lars_code: 337,
    standard_title: 'Data scientist (integrated degree)',
    provider_name: 'University of Nottingham',
    role_type: 'data_science',
    score: 80,
    score_breakdown: null,
    salary_min: 24000,
    salary_max: null,
    salary_text: '£24,000 a year',
    posted_date: '2026-10-01',
    closing_date: '2027-02-17',
    start_date: '2027-09-01',
    locations: [
      {
        text: 'Crawley, RH10 9HA',
        city: 'Crawley',
        region: 'South East',
        nation: 'England',
        lat: 51.11,
        lon: -0.18,
      },
    ],
    primary_city: 'Crawley',
    region: 'South East',
    nation: 'England',
    is_national: false,
    first_seen_at: '2026-10-09T06:30:00Z',
    last_seen_at: '2026-10-09T06:30:00Z',
    is_active: true,
    closed_reason: null,
    status: 'none',
    hidden: false,
    hidden_at: null,
    applied_at: null,
    tracking_updated_at: null,
    sources: [{ source: 'faa', url: 'https://www.findapprenticeship.service.gov.uk/x' }],
    notes_count: 0,
    ...over,
  };
}

export const settings: SettingsRow = {
  id: 1,
  home_postcode: 'LS1 4BN',
  home_lat: 53.7948,
  home_lon: -1.5537,
  preferred_levels: [6, 5, 4],
  preferred_roles: ['data_science', 'data_analyst', 'ml_ai'],
  default_distance_miles: 50,
  digest_min_score: 40,
  digest_enabled: true,
  updated_at: '2026-10-09T00:00:00Z',
};
